node-red-metasix:
  restart: always
  image: node-red
  ports:
    - 1880:1880
#  links:
#    - mongo
  volumes:
    - ./flows.json:/data/flows.json
    - ./settings.js:/data/settings.js

#mongo:
#  restart: always
# image: mongo
#  ports:
#    - 27017:27017
#  volumes:
#    - ./volumes/data/db:/data/db
